name: Black

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  blackcheck:
    name: GitHub Action for Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Action for Black
        uses: jpetrucciani/black-check@master
        with:
          path: "."
