name: Black

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  blackcheck:
    name: GitHub Action for Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for Black
        uses: ricardochaves/python-lint@v1.1.0
        with:
          use-black: true
          extra-black-options: ""
